In [3]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

def get_dist(a, b):
    return np.sqrt(np.sum((a-b)**2))

def kmeans(x, k, it=100):
    c = x[np.random.choice(len(x), k, replace=False)]
    for _ in range(it):
        lab = np.argmin([[get_dist(p, m) for m in c] for p in x], axis=1)
        new_c = []
        for i in range(k):
            pts = x[lab==i]
            new_c.append(pts.mean(axis=0) if len(pts)>0 else c[i])
        c = np.array(new_c)
    return lab, c

data = load_iris()
X = data.data
sc = StandardScaler()
X = sc.fit_transform(X)

labels, centers = kmeans(X, 3)
print(labels[:20])
print(centers)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[-1.01457897  0.85326268 -1.30498732 -1.25489349]
 [-0.01139555 -0.87600831  0.37707573  0.31115341]
 [ 1.16743407  0.14530299  1.00302557  1.0300019 ]]
